sQuiz-2/Core

packages/server/src/games/quiz.ts
packages/server/src/player.ts

First PR, small changes, adds the feature streak feature + additional points for 1st, 2nd and 3rd.
Relates to https://github.com/sQuiz-2/Core/issues/6

Add speed and streak points counter

---

packages/server/src/games/quiz.ts
packages/server/src/player.ts

**Done**
Only 4 guess per round, an almost correct answer don't remove a guess.
**TBD**
- Detect YES OR NO QUESTION, because there should only be 1 guess.
- Send information to the client to display how many guess are left.

server: maximum number of guess per round

---

packages/api/app/Models/Round.ts
packages/api/database/migrations/1603640903357_rounds.ts
packages/api/database/seeders/Default.ts
packages/server/src/games/quiz.ts

I think this will allow us to do the logic we wanted in https://github.com/sQuiz-2/Core/issues/11

add max number of rounds logic

---

packages/server/src/player.ts

fix(server): default score for good answer set to 4

---

packages/server/src/games/quiz.ts
packages/server/src/player.ts

fix(server): reset player streak for new game

---

packages/client/src/components/ScoreBoard/ScoreBoard.tsx
packages/client/src/components/ScoreBoard/ScoreBoardContent.tsx
packages/client/src/components/ScoreBoard/playerRow.tsx
packages/client/src/global/playerInfoState.ts
packages/client/src/utils/players.ts

also remove temporarily remove avatars in scoreboard

Display player's position

---

packages/api/app/Enums/Difficulty.ts
packages/client/src/components/GameMainScreen/QuizMainScreen.tsx
packages/server/src/games/quiz.ts

Start of a PR to add XP and levels. We still need to persist the XP / level with the database based on user ID / session.

add xp multiplier based on difficulty

---

packages/backend/app/Class/Quiz.ts
packages/backend/app/Models/Answer.ts
packages/backend/app/Validators/RoundValidator.ts
packages/backend/database/migrations/1605057180872_answer_reworks.ts
packages/backend/database/seeders/Default.ts
packages/client/src/screens/Add.tsx

Tentative to fix https://github.com/sQuiz-2/Core/issues/27
This will add a bunch of prefixes automatically to each answer.
Possible following improvement: Some numbers might want to be accepted in both forms, digits or words.
For example, "How many astrological signs exists?" we might want to accept both `12` and `douze`

add several possible answers values for each answers

---

.gitignore
README.md
package.json
packages/backend/database/seeders/Default.ts
packages/client/App.tsx
packages/client/app.json
packages/client/metro.config.js
packages/client/package.json
packages/client/tsconfig.json
packages/client/webpack.config.js
packages/shared/package.json
scripts/init.sh
scripts/reset.sh
yarn.lock

Add some scripts to init/reset the project
Auto refresh the frontend when a file in shared is save

Improve dev experience

---

packages/backend/app/Class/Player.ts
packages/backend/app/Class/Quiz.ts
packages/backend/app/Class/Room.ts
packages/backend/app/Class/RoomPool.ts
packages/client/src/screens/Room/GameEnd/Details/Results/GameEndResult.tsx
packages/client/src/screens/Room/GameInProgress/GameInPrgress/GameInProgress.tsx
packages/client/src/screens/Room/GameInProgress/Question/Question.tsx
packages/client/src/screens/Room/GameInProgress/RoundEnd/RoundEnd/RoundEnd.tsx
packages/shared/src/enums/Game.ts
packages/shared/src/enums/Room.ts
packages/shared/src/enums/index.ts
packages/shared/src/typings/Room.ts

Refractor server

---

packages/backend/app/Class/Player.ts
packages/backend/app/Class/Quiz.ts
packages/backend/app/Class/Room.ts
packages/client/src/components/SocketError/SocketError.tsx
packages/client/src/components/SocketError/SocketErrorStyle.tsx
packages/client/src/components/SocketError/index.ts
packages/client/src/screens/Room/Room/Room.tsx
packages/client/src/utils/hooks/socketConnect.ts
packages/shared/src/enums/Room.ts
packages/shared/src/enums/index.ts

Limit players to one connection

Room limit connections

---

packages/backend/app/Class/Home.ts
packages/backend/app/Class/Room.ts
packages/backend/start/socket.ts
packages/client/src/components/SocketError/SocketError.tsx
packages/client/src/screens/Home/Home/Home.tsx
packages/client/src/utils/hooks/socketConnect.ts
packages/shared/src/enums/Room.ts

Add rooms errors
(Max players, max connections per ip...)

Room errors

---

packages/backend/app/Controllers/Http/AuthController.ts
packages/backend/app/Models/User.ts
packages/backend/database/migrations/1608212616751_users.ts
packages/client/src/utils/hooks/oAuthTwitch.ts

The player can update his email so we rely on the user id who can not change

Rely on the oauth id and not on the email

---

packages/backend/app/Class/Player.ts
packages/backend/app/Class/Room.ts
packages/client/src/components/SocketError/SocketError.tsx
packages/client/src/global/userState.ts
packages/client/src/screens/Home/Home/Home.tsx
packages/shared/src/enums/Room.ts

Update room in the lobby when a player join/leave it
Don't keep guess player connected

Socket issues

---

packages/backend/app/Class/Quiz.ts
packages/backend/app/Class/RoundsFetcher.ts
packages/backend/app/Models/Round.ts
packages/backend/database/migrations/1609346209771_rounds.ts
packages/client/src/screens/Home/Home/Home.tsx

Create a boolean column for rounds to fetch only the not played rounds.
Reset this boolean when all the rounds have been played

Random rounds

---

packages/shared/src/enums/Difficulty.ts

This difficulty will allow us to sort questions

Add unknown difficulty

---

packages/shared/src/functions/Answer.ts
packages/shared/tests/Answer.spec.ts

remove prefix 'sur' and keep prefix if there are no following words

improve answer parsing

---

packages/backend/app/Class/Player.ts
packages/backend/app/Class/Room.ts
packages/client/src/global/Room/roomInfos.ts
packages/client/src/screens/Room/GameInProgress/GameInput/GameInput/GameInput.tsx
packages/client/src/screens/Room/GameInProgress/GameInput/GameInput/GameInputStyle.tsx
packages/client/src/screens/Room/GameInProgress/GameInput/GameInput/useCheatTab.ts
packages/client/src/screens/Room/Room/hooks/useRoomInfosListener.ts
packages/shared/src/typings/Room.ts
packages/shared/src/typings/index.ts

Players can't go on another window and then comeback to put an answer. This feature can be enable or disable on each rooms. Staff members are not affected

Remove tab change

---

packages/backend/app/Controllers/Http/ScoreboardsController.ts
packages/backend/start/routes.ts
packages/backend/start/routes/Scoreboard.ts
packages/client/src/constant/navBar.json
packages/client/src/navigation/HomeStack.tsx
packages/client/src/navigation/Linking.ts
packages/client/src/screens/FAQ/FAQ.tsx
packages/client/src/screens/Scoreboard/Scoreboard/Scoreboard.tsx
packages/client/src/screens/Scoreboard/Scoreboard/ScoreboardStyle.tsx
packages/client/src/screens/Scoreboard/Scoreboard/index.ts
packages/client/src/screens/Scoreboard/index.ts
packages/client/src/typings/navigation.ts
packages/client/web/index.html

display player with the higher lvl, most win, most correct answers

Add home scoreboard

---

packages/client/src/components/Header/NavBar/NavBar.tsx
packages/client/src/screens/CustomRoom/JoinRoom/JoinRoom.tsx
packages/client/src/screens/Room/GameInProgress/GameInput/GameInput/useCheatTab.ts
packages/client/src/screens/Stats/Stats.tsx

Remove numeric keyboard for the join private game input, if the anti cheat is not enable in a
private game it should work as excepted, add missing default message in stats

Fix some details (read desc for more infos)

---

packages/backend/app/Controllers/Http/AuthController.ts
packages/backend/app/Utils/Random.ts

Give a random avatar for new players
